### ISSUE TITLE
Mobile friendly ?

### ISSUE THREAD

**Issue by KHannibal** [chemiker/e.nigma-2015#1]
Hi chemiker,
I've come across your blog and ended up here because I'm planning to use your theme (with your button plugin, it's really amazing). You did a very good job, congratulations ! :+1:
However, it seems the theme isn't mobile friendly. I'm not sure whether you built it so that it's responsive. Texts are really small, as well as the menu bar (among other things). Do you plan to add this feature in the future ?
Thanks for your answer !
Cheers, 
K

**Comment by chemiker** [comment]
Hey,

first of all sorry for the late answer. I simply missed your comment.

Well to be honest this theme features some minor mobile compatibility. I checked the theme on my personal devices and text size and other features worked fine. However, I understand what you mean. Mobile compatibility are on my list but at the moment I cannot give you a date when this version will be released.

**Comment by chemiker** [comment]
Yes, it took me only four years to finally do this. Fixed with #a1d0ded
